replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: "nidexiong/ubuntu-ssh"
  tag: "20.04"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 22

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: "local"

env:
  env1:
    name: "UBUNTU_VERSION"
    value: "20.04"
