replicaCount: 1

image:
  imageRegistry: "docker.io"
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: "standard"

env:
  env1:
    name: NODE_ENV
    value: production
  env2:
    name: DEBUG
    value: "false"
