apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-server-ssr.fullname" . }}-tls
  labels:
    {{- include "code-server-ssr.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- include "code-server-ssr.gen-certs" . | nindent 2 }}